version: '3'

services:
  frontend:
    image: snibox/nginx-puma:1.15.9
    ports:
      - "8000:80"
    volumes:
      - static-files:/var/www/html
    depends_on:
      - backend

  backend:
    image: snibox/snibox:latest
    command: sh -c "rm -rf tmp/pids && ./bin/rails s -p 3000 -b '0.0.0.0'"
    environment:
      DB_NAME: "postgres"
      DB_USER: "postgres"
      DB_PASS: "MVPwu1314"
      DB_HOST: "database"
      DB_PORT: "5432"
      FORCE_SSL: "false"
      SECRET_KEY_BASE: "MVPwu1314"
    volumes:
      - static-files:/app/public
    depends_on:
      - database

  database:
    image: postgres:10.7-alpine
    environment:
      POSTGRES_PASSWORD: MVPwu1314
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
  static-files:
